//this file is generated by GameplayTagXMLParser
using System.Collections.Generic;
public static class GameplayTagFlags
{
	public static readonly Dictionary<string, string> TagLookup = new Dictionary<string, string>()
	{
		{ "NONE", "NONE" },
		{ "MOVEMENT", "MOVEMENT" },
		{ "NORMAL_MOVEMENT_DISABLED", "MOVEMENT.NORMAL_MOVEMENT_DISABLED" },
		{ "MOVEMENT_DASHING", "MOVEMENT.MOVEMENT_DASHING" },
		{ "KNOCKBACK", "MOVEMENT.KNOCKBACK" },
		{ "KNOCKBACK_IMMUNITY", "MOVEMENT.KNOCKBACK_IMMUNITY" },
		{ "INTERACTION", "INTERACTION" },
		{ "ABILITY", "ABILITY" },
		{ "ABILITY_MOVEMENT", "ABILITY.ABILITY_MOVEMENT" },
		{ "ABILITY_CC", "ABILITY.ABILITY_CC" },
		{ "ABILITY_DAMAGE", "ABILITY.ABILITY_DAMAGE" },
		{ "STATUS", "STATUS" },
		{ "INVULNERABLE", "STATUS.INVULNERABLE" },
		{ "MOVEMENT_EFFECTED", "STATUS.MOVEMENT_EFFECTED" },
		{ "MOVEMENT_DISABLED", "STATUS.MOVEMENT_EFFECTED.MOVEMENT_DISABLED" },
		{ "CASTING_EFFECTED", "STATUS.CASTING_EFFECTED" },
		{ "CASTING_DISABLED", "STATUS.CASTING_EFFECTED.CASTING_DISABLED" },
		{ "ATTACKING_EFFECTED", "STATUS.ATTACKING_EFFECTED" },
		{ "ATTACKING_DISABLED", "STATUS.ATTACKING_EFFECTED.ATTACKING_DISABLED" },
		{ "INVISIBLE", "STATUS.INVISIBLE" },
	};
	public static string NONE { get => "NONE"; }
		public static string MOVEMENT { get => "MOVEMENT"; }
			public static string NORMAL_MOVEMENT_DISABLED { get => "MOVEMENT.NORMAL_MOVEMENT_DISABLED"; }
			public static string MOVEMENT_DASHING { get => "MOVEMENT.MOVEMENT_DASHING"; }
			public static string KNOCKBACK { get => "MOVEMENT.KNOCKBACK"; }
			public static string KNOCKBACK_IMMUNITY { get => "MOVEMENT.KNOCKBACK_IMMUNITY"; }
		public static string INTERACTION { get => "INTERACTION"; }
		public static string ABILITY { get => "ABILITY"; }
			public static string ABILITY_MOVEMENT { get => "ABILITY.ABILITY_MOVEMENT"; }
			public static string ABILITY_CC { get => "ABILITY.ABILITY_CC"; }
			public static string ABILITY_DAMAGE { get => "ABILITY.ABILITY_DAMAGE"; }
		public static string STATUS { get => "STATUS"; }
			public static string INVULNERABLE { get => "STATUS.INVULNERABLE"; }
			public static string MOVEMENT_EFFECTED { get => "STATUS.MOVEMENT_EFFECTED"; }
				public static string MOVEMENT_DISABLED { get => "STATUS.MOVEMENT_EFFECTED.MOVEMENT_DISABLED"; }
			public static string CASTING_EFFECTED { get => "STATUS.CASTING_EFFECTED"; }
				public static string CASTING_DISABLED { get => "STATUS.CASTING_EFFECTED.CASTING_DISABLED"; }
			public static string ATTACKING_EFFECTED { get => "STATUS.ATTACKING_EFFECTED"; }
				public static string ATTACKING_DISABLED { get => "STATUS.ATTACKING_EFFECTED.ATTACKING_DISABLED"; }
			public static string INVISIBLE { get => "STATUS.INVISIBLE"; }
}
