//this class is generated by GameplayTagXMLParser
public static class GameplayTagFlags
{
	public static string NONE { get => "NONE"; }
		public static string MOVEMENT { get => "MOVEMENT"; }
			public static string NORMAL_MOVEMENT_DISABLED { get => "MOVEMENT.NORMAL_MOVEMENT_DISABLED"; }
			public static string MOVEMENT_DASHING { get => "MOVEMENT.MOVEMENT_DASHING"; }
			public static string KNOCKBACK { get => "MOVEMENT.KNOCKBACK"; }
			public static string KNOCKBACK_IMMUNITY { get => "MOVEMENT.KNOCKBACK_IMMUNITY"; }
		public static string INTERACTION { get => "INTERACTION"; }
		public static string ABILITY { get => "ABILITY"; }
			public static string ABILITY_MOVEMENT { get => "ABILITY.ABILITY_MOVEMENT"; }
			public static string ABILITY_CC { get => "ABILITY.ABILITY_CC"; }
			public static string ABILITY_DAMAGE { get => "ABILITY.ABILITY_DAMAGE"; }
		public static string STATUS { get => "STATUS"; }
			public static string INVULNERABLE { get => "STATUS.INVULNERABLE"; }
			public static string MOVEMENT_EFFECTED { get => "STATUS.MOVEMENT_EFFECTED"; }
				public static string MOVEMENT_DISABLED { get => "STATUS.MOVEMENT_EFFECTED.MOVEMENT_DISABLED"; }
			public static string CASTING_EFFECTED { get => "STATUS.CASTING_EFFECTED"; }
				public static string CASTING_DISABLED { get => "STATUS.CASTING_EFFECTED.CASTING_DISABLED"; }
			public static string ATTACKING_EFFECTED { get => "STATUS.ATTACKING_EFFECTED"; }
				public static string ATTACKING_DISABLED { get => "STATUS.ATTACKING_EFFECTED.ATTACKING_DISABLED"; }
			public static string INVISIBLE { get => "STATUS.INVISIBLE"; }
}